/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import javax.swing.JButton;
import javax.swing.JList;
import javax.swing.JTextArea;

/**
 *
 * @author fakhri
 */
public class LihatBarang extends javax.swing.JFrame {

    /**
     * Creates new form LihatBarang
     */
    public LihatBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kmblbtn = new javax.swing.JButton();
        hapusbtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lsIdBarang = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        taDetail = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(780, 480));
        setPreferredSize(new java.awt.Dimension(780, 480));
        getContentPane().setLayout(null);

        kmblbtn.setText("Kembali");
        getContentPane().add(kmblbtn);
        kmblbtn.setBounds(630, 400, 90, 23);

        hapusbtn.setText("Hapus");
        getContentPane().add(hapusbtn);
        hapusbtn.setBounds(270, 390, 80, 23);

        jScrollPane2.setViewportView(lsIdBarang);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(37, 88, 221, 290);

        taDetail.setColumns(20);
        taDetail.setRows(5);
        jScrollPane3.setViewportView(taDetail);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(264, 88, 461, 290);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Lihat Barang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(364, 16, 134, 29);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID Barang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(37, 60, 80, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Detail");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(264, 60, 44, 22);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\PBO\\warehouse-building-example-04.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 760, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void addActionListener(ActionListener e){
        kmblbtn.addActionListener(e);
        hapusbtn.addActionListener(e);
        
    }

    public String getTaDetail() {
        return taDetail.getText();
    }

    public void setTaDetail(String taDetail) {
        this.taDetail.setText(taDetail);
    }
    
    public JList getListID() {
        return lsIdBarang;
    }
    
    public void setListID(String[] isID) {
        lsIdBarang.setListData(isID);
    }
    

    public void setLsBarang(String[] ListBarang) {
        lsIdBarang.setListData(ListBarang);
    }
    
    
    public JButton getKmblbtn() {
        return kmblbtn;
    }

    public void setKmblbtn(JButton kmblbtn) {
        this.kmblbtn = kmblbtn;
    }

    public JButton getHapusbtn() {
        return hapusbtn;
    }

    public void setHapusbtn(JButton hapusbtn) {
        this.hapusbtn = hapusbtn;
    }
    public String getSelectedID(){
        return lsIdBarang.getSelectedValue();
    }
    
    public void addMouseAdapter(MouseAdapter e){
        lsIdBarang.addMouseListener(e);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hapusbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton kmblbtn;
    private javax.swing.JList<String> lsIdBarang;
    private javax.swing.JTextArea taDetail;
    // End of variables declaration//GEN-END:variables
}
