/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author fakhri
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    public String getPnameF() {
        return String.valueOf(PnameF.getPassword());
    }

    public void setPnameF(JPasswordField PnameF) {
        this.PnameF = PnameF;
    }

    public String getUnameF() {
        return UnameF.getText();
    }

    public void setUnameF(String s) {
        this.UnameF.setText(s);
    }
    
    public JButton getCancelbtn() {
        return cancelbtn;
    }

    public void setCancelbtn(JButton cancelbtn) {
        this.cancelbtn = cancelbtn;
    }

    public JButton getLoginbtn() {
        return loginbtn;
    }

    public void setLoginbtn(JButton loginbtn) {
        this.loginbtn = loginbtn;
    }
    
     public void addActionListener(ActionListener e){
        cancelbtn.addActionListener(e);
        loginbtn.addActionListener(e);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UnameF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        cancelbtn = new javax.swing.JButton();
        PnameF = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(402, 306));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("LOGIN ADMIN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 180, 46);

        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 100, 100, 14);

        UnameF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UnameFActionPerformed(evt);
            }
        });
        getContentPane().add(UnameF);
        UnameF.setBounds(140, 100, 198, 20);

        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 150, 100, 14);

        loginbtn.setText("Login");
        getContentPane().add(loginbtn);
        loginbtn.setBounds(80, 210, 70, 23);

        cancelbtn.setText("Cancel");
        getContentPane().add(cancelbtn);
        cancelbtn.setBounds(230, 210, 90, 23);
        getContentPane().add(PnameF);
        PnameF.setBounds(140, 150, 198, 20);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\PBO\\rack2-1024x660.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 400, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UnameFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UnameFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UnameFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PnameF;
    private javax.swing.JTextField UnameF;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton loginbtn;
    // End of variables declaration//GEN-END:variables
}
