/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author fakhri
 */
public class MasukBarang extends javax.swing.JFrame {


    /**
     * Creates new form MasukBarang
     */
    public MasukBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NmCustF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        idBrgF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        nmBrgF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jmlBrgF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        brtBrgF = new javax.swing.JTextField();
        msknBrgbtn = new javax.swing.JButton();
        btlBrgbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ReceiverF = new javax.swing.JTextField();
        CheckerF = new javax.swing.JTextField();
        PickerF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(472, 380));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Masukan Barang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 11, 200, 29);

        jLabel3.setText("Nama");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 61, 110, 14);
        getContentPane().add(NmCustF);
        NmCustF.setBounds(166, 58, 236, 20);

        jLabel4.setText("ID Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 87, 110, 14);
        getContentPane().add(idBrgF);
        idBrgF.setBounds(166, 84, 236, 20);

        jLabel5.setText("Nama Barang");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 113, 110, 14);
        getContentPane().add(nmBrgF);
        nmBrgF.setBounds(166, 110, 236, 20);

        jLabel6.setText("Jumlah");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 139, 110, 14);
        getContentPane().add(jmlBrgF);
        jmlBrgF.setBounds(166, 136, 236, 20);

        jLabel7.setText("Berat");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 165, 110, 14);
        getContentPane().add(brtBrgF);
        brtBrgF.setBounds(166, 162, 236, 20);

        msknBrgbtn.setText("Masukan");
        getContentPane().add(msknBrgbtn);
        msknBrgbtn.setBounds(80, 290, 90, 23);

        btlBrgbtn.setText("Back");
        getContentPane().add(btlBrgbtn);
        btlBrgbtn.setBounds(330, 290, 75, 23);

        jLabel2.setText("Receiver");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 191, 110, 14);

        jLabel8.setText("Checker");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(53, 217, 110, 14);

        jLabel9.setText("Picker");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(53, 243, 110, 14);

        ReceiverF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceiverFActionPerformed(evt);
            }
        });
        getContentPane().add(ReceiverF);
        ReceiverF.setBounds(166, 188, 236, 20);
        getContentPane().add(CheckerF);
        CheckerF.setBounds(166, 214, 236, 20);
        getContentPane().add(PickerF);
        PickerF.setBounds(166, 240, 236, 20);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, -10, 470, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReceiverFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceiverFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReceiverFActionPerformed

    public void addActionListener(ActionListener e){
        msknBrgbtn.addActionListener(e);
        btlBrgbtn.addActionListener(e);
    }
    
    public String getNama_Customer() {
        return this.NmCustF.getText();
    }

    public void setNama_Customer(String s) {
        this.NmCustF.setText(s);
    }

    public String getBerat() {
        return this.brtBrgF.getText();
    }

    public void setBerat(int s) {
        this.brtBrgF.setText(String.valueOf(s));
    }

    public JButton getBtlBrgbtn() {
        return btlBrgbtn;
    }
    
    public void setBtlBrgbtn(JButton btlBrgbtn) {
        this.btlBrgbtn = btlBrgbtn;
    }

    public String getID_Barang() {
        return this.idBrgF.getText();
    }

    public void setID_Barang(String s) {
        this.idBrgF.setText(s);
    }

    public String getJumlah() {
        return this.jmlBrgF.getText();
    }

    public void setJumlah(int s) {
        this.jmlBrgF.setText(String.valueOf(s));
    }

    public JButton getMsknBrgbtn() {
        return msknBrgbtn;
    }

    public void setMsknBrgbtn(JButton msknBrgbtn) {
        this.msknBrgbtn = msknBrgbtn;
    }

    public String getNama_Barang() {
        return this.nmBrgF.getText();
    }
    
    public void setNama_Barang(String s) {
        this.nmBrgF.setText(s);
    }

    public String getCheckerF() {
        return this.CheckerF.getText();
    }

    public void setCheckerF(String s) {
        this.CheckerF.setText(s);
    }

    public String getPickerF() {
        return this.PickerF.getText();
    }

    public void setPickerF(String s) {
        this.PickerF.setText(s);
    }

    public String getReceiverF() {
        return this.ReceiverF.getText();
    }

    public void setReceiverF(String s) {
        this.ReceiverF.setText(s);
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasukBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasukBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CheckerF;
    private javax.swing.JTextField NmCustF;
    private javax.swing.JTextField PickerF;
    private javax.swing.JTextField ReceiverF;
    private javax.swing.JTextField brtBrgF;
    private javax.swing.JButton btlBrgbtn;
    private javax.swing.JTextField idBrgF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jmlBrgF;
    private javax.swing.JButton msknBrgbtn;
    private javax.swing.JTextField nmBrgF;
    // End of variables declaration//GEN-END:variables
}
