/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author fakhri
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        masukbtn = new javax.swing.JButton();
        lihatbtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 330));
        setSize(new java.awt.Dimension(400, 301));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menu Gudang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 170, 29);

        masukbtn.setText("Masukan Barang");
        masukbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masukbtnActionPerformed(evt);
            }
        });
        getContentPane().add(masukbtn);
        masukbtn.setBounds(93, 86, 214, 37);

        lihatbtn.setText("Lihat");
        getContentPane().add(lihatbtn);
        lihatbtn.setBounds(90, 160, 214, 37);

        logoutbtn.setText("Log Out");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn);
        logoutbtn.setBounds(150, 240, 100, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\PBO\\warehouse.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-270, 0, 750, 320);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void masukbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masukbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_masukbtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void addActionListener(ActionListener e){
        masukbtn.addActionListener(e);
        lihatbtn.addActionListener(e);
        logoutbtn.addActionListener(e);
    }

    
    public void setLihatbtn(JButton lihatbtn){
        this.lihatbtn = lihatbtn;
    }

    public void setLogoutbtn(JButton logoutbtn) {
        this.logoutbtn = logoutbtn;
    }

    public void setMasukbtn(JButton masukbtn) {
        this.masukbtn = masukbtn;
    }

    /**
     * @param args the command line arguments
     */

    public JButton getMasukbtn() {
        return this.masukbtn;
    }
    
    
    public JButton getLihatbtn(){
        return this.lihatbtn;
    }
    
    public JButton getLogoutbtn(){
        return this.logoutbtn;
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton lihatbtn;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton masukbtn;
    // End of variables declaration//GEN-END:variables
}
